## Zabudované funkcie

In [1]:
import pandas as pd

In [5]:
first_names = pd.read_csv('bank_users.csv')['first_name']
first_names.head()
# načíta textový stĺpec zo súboru ako Series

0       Shawn
1    Sergeant
2    Ambrosio
3        Gram
4       Britt
Name: first_name, dtype: object

In [7]:
bank_account = pd.read_csv("bank_users.csv")["bank_account"]
bank_account.head()
# načíta číselný stĺpec zo súboru ako Series

0    58.0
1    70.0
2    48.0
3    92.0
4    78.0
Name: bank_account, dtype: float64

In [15]:
len(first_names)
# dĺžka, počet riadkov v Series

200

In [17]:
len(bank_account)

200

In [19]:
type(first_names)
# vráti dátový typ

pandas.core.series.Series

In [21]:
type(bank_account)

pandas.core.series.Series

In [24]:
list(first_names)
# vráti zoznam/list

['Shawn',
 'Sergeant',
 'Ambrosio',
 'Gram',
 'Britt',
 'Onfroi',
 'Dex',
 'Charles',
 'Ivory',
 'Quintilla',
 'Munroe',
 'Charmion',
 'Suzann',
 'Rennie',
 'Nichole',
 'Lydia',
 'Quent',
 'Willi',
 'Ferd',
 'Catlaina',
 'Mikael',
 'Selena',
 'Alec',
 'Isa',
 'Meara',
 'Tracie',
 'Harriott',
 'Mathew',
 'Mattias',
 'Barde',
 'Ralph',
 'Nicol',
 'Catrina',
 'Glenn',
 'Ortensia',
 'Gert',
 'Barbara',
 'Jeffy',
 'Hobie',
 'Calv',
 'Lilas',
 'Mirabella',
 'Ophelie',
 'Tessi',
 'Roarke',
 'Wilek',
 'Verile',
 'Pacorro',
 'Dav',
 'Robbin',
 'Janot',
 'Luisa',
 'Murray',
 'Selie',
 'Euphemia',
 'Hilde',
 'Kaleena',
 'Drusi',
 'Andre',
 'Misti',
 'Joby',
 'Dorie',
 'Florida',
 'Wesley',
 'Lilith',
 'Shaun',
 'Netti',
 'Roma',
 'Marci',
 'Rutger',
 'Nealson',
 'Petronia',
 'Elfrida',
 'Raphael',
 'Katerine',
 'Stuart',
 'Alic',
 'Corrinne',
 'Lorettalorna',
 'Silvana',
 'Lizbeth',
 'Joshuah',
 'Tamra',
 'Carissa',
 'Dolores',
 'Annecorinne',
 'Myrle',
 'Annie',
 'Maye',
 'Ganny',
 'Kimmy',
 'Fair',
 'Selig',
 'Jere',
 'Willy',
 'Emera',
 'Emmeline',
 'Garnet',
 'Dwayne',
 'Gleda',
 'Arnuad',
 'Giacinta',
 'Biddie',
 'Omar',
 'Lynda',
 'Mollie',
 'Ora',
 'Clari',
 'Sebastian',
 'Joachim',
 'Krystyna',
 'Wilbur',
 'Blake',
 'Brander',
 'Thaine',
 'Robyn',
 'Creight',
 'Ciel',
 'Thibaud',
 'Eldon',
 'Mimi',
 'Tobit',
 'Donia',
 'Paula',
 'Hedy',
 'Cindra',
 'Chilton',
 'Lanni',
 'Betteanne',
 'Ileane',
 'Antoine',
 'Frannie',
 'Georgianne',
 'Mace',
 'Myles',
 'Raddie',
 'Christen',
 'Retha',
 'Goober',
 'Evelyn',
 'Adham',
 'Mauricio',
 'Nonna',
 'Netta',
 'Gigi',
 'Francklyn',
 'Bartie',
 'Hallsy',
 'Lancelot',
 'Wenda',
 'Aila',
 'Buddie',
 'Krystyna',
 'Harriet',
 'Roderick',
 'Petra',
 'Kale',
 'Mercy',
 'Lannie',
 'Sarina',
 'Gloriana',
 'Robinet',
 'Olimpia',
 'Rosa',
 'Annabell',
 'Jarrod',
 'Morgun',
 'Calv',
 'Bryn',
 'Cathi',
 'Arabela',
 'Vikki',
 'Cleopatra',
 'Demetra',
 'Damon',
 'Jefferey',
 'Stephanie',
 'Georgeanne',
 'Julie',
 'Dexter',
 'Lishe',
 'Ignacio',
 'Neel',
 'Caroline',
 'Claudette',
 'Consuela',
 'Jenda',
 'Coralyn',
 'Deidre',
 'Jacquenetta',
 'Archibaldo',
 'Cathrine',
 'Gram',
 'Perle',
 'Brennan',
 'Franz',
 'Adolphus',
 'Aurelea',
 'Armstrong',
 'Henrietta']

In [26]:
list(bank_account)

[58.0,
 70.0,
 48.0,
 92.0,
 78.0,
 58.0,
 36.0,
 nan,
 48.0,
 24.0,
 nan,
 62.0,
 44.0,
 95.0,
 43.0,
 48.0,
 24.0,
 nan,
 30.0,
 24.0,
 34.0,
 42.0,
 73.0,
 43.0,
 19.0,
 nan,
 25.0,
 nan,
 33.0,
 72.0,
 89.0,
 31.0,
 53.0,
 71.0,
 10.0,
 50.0,
 29.0,
 79.0,
 58.0,
 56.0,
 42.0,
 33.0,
 81.0,
 95.0,
 94.0,
 nan,
 94.0,
 72.0,
 27.0,
 100.0,
 94.0,
 98.0,
 93.0,
 90.0,
 32.0,
 93.0,
 82.0,
 56.0,
 72.0,
 28.0,
 45.0,
 48.0,
 52.0,
 44.0,
 66.0,
 10.0,
 59.0,
 15.0,
 31.0,
 47.0,
 97.0,
 91.0,
 nan,
 13.0,
 88.0,
 78.0,
 18.0,
 33.0,
 72.0,
 nan,
 56.0,
 72.0,
 48.0,
 nan,
 94.0,
 84.0,
 79.0,
 97.0,
 45.0,
 11.0,
 27.0,
 34.0,
 68.0,
 95.0,
 33.0,
 18.0,
 97.0,
 64.0,
 52.0,
 75.0,
 69.0,
 28.0,
 nan,
 34.0,
 57.0,
 25.0,
 54.0,
 nan,
 65.0,
 nan,
 63.0,
 nan,
 24.0,
 74.0,
 58.0,
 16.0,
 71.0,
 nan,
 35.0,
 40.0,
 84.0,
 91.0,
 35.0,
 85.0,
 57.0,
 11.0,
 53.0,
 100.0,
 16.0,
 88.0,
 68.0,
 88.0,
 55.0,
 nan,
 58.0,
 82.0,
 93.0,
 27.0,
 55.0,
 93.0,
 55.0,
 32.0,
 43.0,
 61.0,
 nan,
 32.0,
 86.0,
 58.0,
 29.0,
 96.0,
 43.0,
 nan,
 69.0,
 47.0,
 82.0,
 68.0,
 71.0,
 90.0,
 61.0,
 68.0,
 46.0,
 21.0,
 73.0,
 21.0,
 85.0,
 21.0,
 nan,
 28.0,
 36.0,
 nan,
 15.0,
 49.0,
 24.0,
 77.0,
 10.0,
 35.0,
 46.0,
 21.0,
 83.0,
 21.0,
 97.0,
 29.0,
 43.0,
 87.0,
 73.0,
 72.0,
 19.0,
 50.0,
 23.0,
 76.0,
 87.0,
 91.0,
 87.0,
 56.0,
 29.0,
 90.0,
 56.0,
 nan,
 87.0,
 nan]

In [28]:
sorted(first_names)
# zoradí textový stĺpec podľa abecedy

['Adham',
 'Adolphus',
 'Aila',
 'Alec',
 'Alic',
 'Ambrosio',
 'Andre',
 'Annabell',
 'Annecorinne',
 'Annie',
 'Antoine',
 'Arabela',
 'Archibaldo',
 'Armstrong',
 'Arnuad',
 'Aurelea',
 'Barbara',
 'Barde',
 'Bartie',
 'Betteanne',
 'Biddie',
 'Blake',
 'Brander',
 'Brennan',
 'Britt',
 'Bryn',
 'Buddie',
 'Calv',
 'Calv',
 'Carissa',
 'Caroline',
 'Cathi',
 'Cathrine',
 'Catlaina',
 'Catrina',
 'Charles',
 'Charmion',
 'Chilton',
 'Christen',
 'Ciel',
 'Cindra',
 'Clari',
 'Claudette',
 'Cleopatra',
 'Consuela',
 'Coralyn',
 'Corrinne',
 'Creight',
 'Damon',
 'Dav',
 'Deidre',
 'Demetra',
 'Dex',
 'Dexter',
 'Dolores',
 'Donia',
 'Dorie',
 'Drusi',
 'Dwayne',
 'Eldon',
 'Elfrida',
 'Emera',
 'Emmeline',
 'Euphemia',
 'Evelyn',
 'Fair',
 'Ferd',
 'Florida',
 'Francklyn',
 'Frannie',
 'Franz',
 'Ganny',
 'Garnet',
 'Georgeanne',
 'Georgianne',
 'Gert',
 'Giacinta',
 'Gigi',
 'Gleda',
 'Glenn',
 'Gloriana',
 'Goober',
 'Gram',
 'Gram',
 'Hallsy',
 'Harriet',
 'Harriott',
 'Hedy',
 'Henrietta',
 'Hilde',
 'Hobie',
 'Ignacio',
 'Ileane',
 'Isa',
 'Ivory',
 'Jacquenetta',
 'Janot',
 'Jarrod',
 'Jefferey',
 'Jeffy',
 'Jenda',
 'Jere',
 'Joachim',
 'Joby',
 'Joshuah',
 'Julie',
 'Kale',
 'Kaleena',
 'Katerine',
 'Kimmy',
 'Krystyna',
 'Krystyna',
 'Lancelot',
 'Lanni',
 'Lannie',
 'Lilas',
 'Lilith',
 'Lishe',
 'Lizbeth',
 'Lorettalorna',
 'Luisa',
 'Lydia',
 'Lynda',
 'Mace',
 'Marci',
 'Mathew',
 'Mattias',
 'Mauricio',
 'Maye',
 'Meara',
 'Mercy',
 'Mikael',
 'Mimi',
 'Mirabella',
 'Misti',
 'Mollie',
 'Morgun',
 'Munroe',
 'Murray',
 'Myles',
 'Myrle',
 'Nealson',
 'Neel',
 'Netta',
 'Netti',
 'Nichole',
 'Nicol',
 'Nonna',
 'Olimpia',
 'Omar',
 'Onfroi',
 'Ophelie',
 'Ora',
 'Ortensia',
 'Pacorro',
 'Paula',
 'Perle',
 'Petra',
 'Petronia',
 'Quent',
 'Quintilla',
 'Raddie',
 'Ralph',
 'Raphael',
 'Rennie',
 'Retha',
 'Roarke',
 'Robbin',
 'Robinet',
 'Robyn',
 'Roderick',
 'Roma',
 'Rosa',
 'Rutger',
 'Sarina',
 'Sebastian',
 'Selena',
 'Selie',
 'Selig',
 'Sergeant',
 'Shaun',
 'Shawn',
 'Silvana',
 'Stephanie',
 'Stuart',
 'Suzann',
 'Tamra',
 'Tessi',
 'Thaine',
 'Thibaud',
 'Tobit',
 'Tracie',
 'Verile',
 'Vikki',
 'Wenda',
 'Wesley',
 'Wilbur',
 'Wilek',
 'Willi',
 'Willy']

In [30]:
sorted(bank_account)
# zoradí číselný stĺpec od najmenšieho

[10.0,
 10.0,
 11.0,
 11.0,
 13.0,
 15.0,
 16.0,
 16.0,
 18.0,
 18.0,
 19.0,
 24.0,
 24.0,
 24.0,
 24.0,
 25.0,
 25.0,
 27.0,
 27.0,
 27.0,
 28.0,
 28.0,
 29.0,
 29.0,
 30.0,
 31.0,
 31.0,
 32.0,
 32.0,
 32.0,
 33.0,
 33.0,
 33.0,
 33.0,
 34.0,
 34.0,
 34.0,
 35.0,
 35.0,
 36.0,
 40.0,
 42.0,
 42.0,
 43.0,
 43.0,
 43.0,
 44.0,
 44.0,
 45.0,
 45.0,
 47.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 50.0,
 52.0,
 52.0,
 53.0,
 53.0,
 54.0,
 55.0,
 55.0,
 55.0,
 56.0,
 56.0,
 56.0,
 57.0,
 57.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 59.0,
 62.0,
 63.0,
 64.0,
 66.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 72.0,
 72.0,
 72.0,
 73.0,
 75.0,
 78.0,
 78.0,
 79.0,
 82.0,
 84.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 nan,
 nan,
 79.0,
 93.0,
 93.0,
 94.0,
 94.0,
 95.0,
 nan,
 nan,
 nan,
 72.0,
 81.0,
 94.0,
 94.0,
 95.0,
 nan,
 95.0,
 97.0,
 97.0,
 98.0,
 nan,
 nan,
 nan,
 97.0,
 100.0,
 nan,
 nan,
 65.0,
 nan,
 nan,
 68.0,
 71.0,
 74.0,
 nan,
 61.0,
 82.0,
 84.0,
 85.0,
 86.0,
 88.0,
 88.0,
 91.0,
 93.0,
 93.0,
 96.0,
 100.0,
 nan,
 nan,
 43.0,
 nan,
 10.0,
 15.0,
 19.0,
 21.0,
 21.0,
 21.0,
 21.0,
 21.0,
 23.0,
 24.0,
 28.0,
 29.0,
 29.0,
 35.0,
 36.0,
 43.0,
 46.0,
 46.0,
 47.0,
 49.0,
 50.0,
 56.0,
 56.0,
 61.0,
 68.0,
 68.0,
 69.0,
 71.0,
 72.0,
 73.0,
 73.0,
 76.0,
 77.0,
 82.0,
 83.0,
 85.0,
 87.0,
 90.0,
 nan,
 nan,
 87.0,
 87.0,
 87.0,
 90.0,
 91.0,
 97.0,
 nan,
 nan]

In [32]:
dict(first_names)
# vytvorí slovník

{0: 'Shawn',
 1: 'Sergeant',
 2: 'Ambrosio',
 3: 'Gram',
 4: 'Britt',
 5: 'Onfroi',
 6: 'Dex',
 7: 'Charles',
 8: 'Ivory',
 9: 'Quintilla',
 10: 'Munroe',
 11: 'Charmion',
 12: 'Suzann',
 13: 'Rennie',
 14: 'Nichole',
 15: 'Lydia',
 16: 'Quent',
 17: 'Willi',
 18: 'Ferd',
 19: 'Catlaina',
 20: 'Mikael',
 21: 'Selena',
 22: 'Alec',
 23: 'Isa',
 24: 'Meara',
 25: 'Tracie',
 26: 'Harriott',
 27: 'Mathew',
 28: 'Mattias',
 29: 'Barde',
 30: 'Ralph',
 31: 'Nicol',
 32: 'Catrina',
 33: 'Glenn',
 34: 'Ortensia',
 35: 'Gert',
 36: 'Barbara',
 37: 'Jeffy',
 38: 'Hobie',
 39: 'Calv',
 40: 'Lilas',
 41: 'Mirabella',
 42: 'Ophelie',
 43: 'Tessi',
 44: 'Roarke',
 45: 'Wilek',
 46: 'Verile',
 47: 'Pacorro',
 48: 'Dav',
 49: 'Robbin',
 50: 'Janot',
 51: 'Luisa',
 52: 'Murray',
 53: 'Selie',
 54: 'Euphemia',
 55: 'Hilde',
 56: 'Kaleena',
 57: 'Drusi',
 58: 'Andre',
 59: 'Misti',
 60: 'Joby',
 61: 'Dorie',
 62: 'Florida',
 63: 'Wesley',
 64: 'Lilith',
 65: 'Shaun',
 66: 'Netti',
 67: 'Roma',
 68: 'Marci',
 69: 'Rutger',
 70: 'Nealson',
 71: 'Petronia',
 72: 'Elfrida',
 73: 'Raphael',
 74: 'Katerine',
 75: 'Stuart',
 76: 'Alic',
 77: 'Corrinne',
 78: 'Lorettalorna',
 79: 'Silvana',
 80: 'Lizbeth',
 81: 'Joshuah',
 82: 'Tamra',
 83: 'Carissa',
 84: 'Dolores',
 85: 'Annecorinne',
 86: 'Myrle',
 87: 'Annie',
 88: 'Maye',
 89: 'Ganny',
 90: 'Kimmy',
 91: 'Fair',
 92: 'Selig',
 93: 'Jere',
 94: 'Willy',
 95: 'Emera',
 96: 'Emmeline',
 97: 'Garnet',
 98: 'Dwayne',
 99: 'Gleda',
 100: 'Arnuad',
 101: 'Giacinta',
 102: 'Biddie',
 103: 'Omar',
 104: 'Lynda',
 105: 'Mollie',
 106: 'Ora',
 107: 'Clari',
 108: 'Sebastian',
 109: 'Joachim',
 110: 'Krystyna',
 111: 'Wilbur',
 112: 'Blake',
 113: 'Brander',
 114: 'Thaine',
 115: 'Robyn',
 116: 'Creight',
 117: 'Ciel',
 118: 'Thibaud',
 119: 'Eldon',
 120: 'Mimi',
 121: 'Tobit',
 122: 'Donia',
 123: 'Paula',
 124: 'Hedy',
 125: 'Cindra',
 126: 'Chilton',
 127: 'Lanni',
 128: 'Betteanne',
 129: 'Ileane',
 130: 'Antoine',
 131: 'Frannie',
 132: 'Georgianne',
 133: 'Mace',
 134: 'Myles',
 135: 'Raddie',
 136: 'Christen',
 137: 'Retha',
 138: 'Goober',
 139: 'Evelyn',
 140: 'Adham',
 141: 'Mauricio',
 142: 'Nonna',
 143: 'Netta',
 144: 'Gigi',
 145: 'Francklyn',
 146: 'Bartie',
 147: 'Hallsy',
 148: 'Lancelot',
 149: 'Wenda',
 150: 'Aila',
 151: 'Buddie',
 152: 'Krystyna',
 153: 'Harriet',
 154: 'Roderick',
 155: 'Petra',
 156: 'Kale',
 157: 'Mercy',
 158: 'Lannie',
 159: 'Sarina',
 160: 'Gloriana',
 161: 'Robinet',
 162: 'Olimpia',
 163: 'Rosa',
 164: 'Annabell',
 165: 'Jarrod',
 166: 'Morgun',
 167: 'Calv',
 168: 'Bryn',
 169: 'Cathi',
 170: 'Arabela',
 171: 'Vikki',
 172: 'Cleopatra',
 173: 'Demetra',
 174: 'Damon',
 175: 'Jefferey',
 176: 'Stephanie',
 177: 'Georgeanne',
 178: 'Julie',
 179: 'Dexter',
 180: 'Lishe',
 181: 'Ignacio',
 182: 'Neel',
 183: 'Caroline',
 184: 'Claudette',
 185: 'Consuela',
 186: 'Jenda',
 187: 'Coralyn',
 188: 'Deidre',
 189: 'Jacquenetta',
 190: 'Archibaldo',
 191: 'Cathrine',
 192: 'Gram',
 193: 'Perle',
 194: 'Brennan',
 195: 'Franz',
 196: 'Adolphus',
 197: 'Aurelea',
 198: 'Armstrong',
 199: 'Henrietta'}

In [34]:
dict(bank_account)

{0: 58.0,
 1: 70.0,
 2: 48.0,
 3: 92.0,
 4: 78.0,
 5: 58.0,
 6: 36.0,
 7: nan,
 8: 48.0,
 9: 24.0,
 10: nan,
 11: 62.0,
 12: 44.0,
 13: 95.0,
 14: 43.0,
 15: 48.0,
 16: 24.0,
 17: nan,
 18: 30.0,
 19: 24.0,
 20: 34.0,
 21: 42.0,
 22: 73.0,
 23: 43.0,
 24: 19.0,
 25: nan,
 26: 25.0,
 27: nan,
 28: 33.0,
 29: 72.0,
 30: 89.0,
 31: 31.0,
 32: 53.0,
 33: 71.0,
 34: 10.0,
 35: 50.0,
 36: 29.0,
 37: 79.0,
 38: 58.0,
 39: 56.0,
 40: 42.0,
 41: 33.0,
 42: 81.0,
 43: 95.0,
 44: 94.0,
 45: nan,
 46: 94.0,
 47: 72.0,
 48: 27.0,
 49: 100.0,
 50: 94.0,
 51: 98.0,
 52: 93.0,
 53: 90.0,
 54: 32.0,
 55: 93.0,
 56: 82.0,
 57: 56.0,
 58: 72.0,
 59: 28.0,
 60: 45.0,
 61: 48.0,
 62: 52.0,
 63: 44.0,
 64: 66.0,
 65: 10.0,
 66: 59.0,
 67: 15.0,
 68: 31.0,
 69: 47.0,
 70: 97.0,
 71: 91.0,
 72: nan,
 73: 13.0,
 74: 88.0,
 75: 78.0,
 76: 18.0,
 77: 33.0,
 78: 72.0,
 79: nan,
 80: 56.0,
 81: 72.0,
 82: 48.0,
 83: nan,
 84: 94.0,
 85: 84.0,
 86: 79.0,
 87: 97.0,
 88: 45.0,
 89: 11.0,
 90: 27.0,
 91: 34.0,
 92: 68.0,
 93: 95.0,
 94: 33.0,
 95: 18.0,
 96: 97.0,
 97: 64.0,
 98: 52.0,
 99: 75.0,
 100: 69.0,
 101: 28.0,
 102: nan,
 103: 34.0,
 104: 57.0,
 105: 25.0,
 106: 54.0,
 107: nan,
 108: 65.0,
 109: nan,
 110: 63.0,
 111: nan,
 112: 24.0,
 113: 74.0,
 114: 58.0,
 115: 16.0,
 116: 71.0,
 117: nan,
 118: 35.0,
 119: 40.0,
 120: 84.0,
 121: 91.0,
 122: 35.0,
 123: 85.0,
 124: 57.0,
 125: 11.0,
 126: 53.0,
 127: 100.0,
 128: 16.0,
 129: 88.0,
 130: 68.0,
 131: 88.0,
 132: 55.0,
 133: nan,
 134: 58.0,
 135: 82.0,
 136: 93.0,
 137: 27.0,
 138: 55.0,
 139: 93.0,
 140: 55.0,
 141: 32.0,
 142: 43.0,
 143: 61.0,
 144: nan,
 145: 32.0,
 146: 86.0,
 147: 58.0,
 148: 29.0,
 149: 96.0,
 150: 43.0,
 151: nan,
 152: 69.0,
 153: 47.0,
 154: 82.0,
 155: 68.0,
 156: 71.0,
 157: 90.0,
 158: 61.0,
 159: 68.0,
 160: 46.0,
 161: 21.0,
 162: 73.0,
 163: 21.0,
 164: 85.0,
 165: 21.0,
 166: nan,
 167: 28.0,
 168: 36.0,
 169: nan,
 170: 15.0,
 171: 49.0,
 172: 24.0,
 173: 77.0,
 174: 10.0,
 175: 35.0,
 176: 46.0,
 177: 21.0,
 178: 83.0,
 179: 21.0,
 180: 97.0,
 181: 29.0,
 182: 43.0,
 183: 87.0,
 184: 73.0,
 185: 72.0,
 186: 19.0,
 187: 50.0,
 188: 23.0,
 189: 76.0,
 190: 87.0,
 191: 91.0,
 192: 87.0,
 193: 56.0,
 194: 29.0,
 195: 90.0,
 196: 56.0,
 197: nan,
 198: 87.0,
 199: nan}

In [36]:
min(first_names)
# vráti prvého v poradí

'Adham'

In [38]:
max(first_names)
# vráti posledného v poradí

'Willy'

In [40]:
min(bank_account)
# vráti namenšie číslo

10.0

In [42]:
max(bank_account)
# vráti najvyššiu hodnotu

100.0